add norsk mirror jobs to the persi pipeline [#168272942](https://www.pivotaltracker.com/story/show/168272942)

diff --git a/persi.yml b/persi.yml
--- a/persi.yml
+++ b/persi.yml
@@ -57,6 +57,9 @@ groups:
   - smbbroker-unit
   - smbdriver-integration
   - smbdriver-unit
+  - norsk-status-nfs
+  - norsk-status-mapfs
+  - norsk-status-smb
 
 - name: upgrade-environment-test-nfs-smb
   jobs:
@@ -139,6 +142,12 @@ groups:
   - manual-bump-mapfs-patch
   - manual-bump-mapfs-minor
   - manual-bump-mapfs-major
+
+- name: norsk
+  jobs:
+  - norsk-status-nfs
+  - norsk-status-mapfs
+  - norsk-status-smb
 
 resources:
 
@@ -394,6 +403,16 @@ resources:
   type: git
   source:
     uri: https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests.git
+
+- name: oslo-scan-status
+  type: git
+  source:
+    private_key: {{norsk_mirror_private_key}}
+    uri: git@github.com:pivotal/oslo-scan-status.git
+    paths:
+    - nfs-volume-release/*
+    - smb-volume-release/*
+    - mapfs-release/*
 
 resource_types:
 - name: pivnet
@@ -2027,3 +2046,90 @@ jobs:
   - put: env-creation-gate-lock
     params:
       release: env-creation-gate-lock
+
+- name: norsk-status-nfs
+  plan:
+  - get: oslo-scan-status
+    trigger: true
+  - task: check-status-file
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source: { repository: ubuntu }
+      inputs:
+      - name: oslo-scan-status
+      run:
+        path: sh
+        args:
+        - -c
+        - |
+          status_file=oslo-scan-status/nfs-volume-release/status.json
+          cat "$status_file"
+          num_failures="$(grep -c '"status": "failed"' $status_file)"
+          echo ""
+          if [ "$num_failures" -eq 0 ]; then
+            echo "No failures found"
+            exit 0
+          else
+            echo "$num_failures failures found! Please check your norsk-viewers pipelines specified in the status.json and resolve the errors. Contact the OSL team if you need help."
+            exit 1
+          fi
+
+- name: norsk-status-mapfs
+  plan:
+  - get: oslo-scan-status
+    trigger: true
+  - task: check-status-file
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source: { repository: ubuntu }
+      inputs:
+      - name: oslo-scan-status
+      run:
+        path: sh
+        args:
+        - -c
+        - |
+          status_file=oslo-scan-status/mapfs-release/status.json
+          cat "$status_file"
+          num_failures="$(grep -c '"status": "failed"' $status_file)"
+          echo ""
+          if [ "$num_failures" -eq 0 ]; then
+            echo "No failures found"
+            exit 0
+          else
+            echo "$num_failures failures found! Please check your norsk-viewers pipelines specified in the status.json and resolve the errors. Contact the OSL team if you need help."
+            exit 1
+          fi
+
+- name: norsk-status-smb
+  plan:
+  - get: oslo-scan-status
+    trigger: true
+  - task: check-status-file
+    config:
+      platform: linux
+      image_resource:
+        type: docker-image
+        source: { repository: ubuntu }
+      inputs:
+      - name: oslo-scan-status
+      run:
+        path: sh
+        args:
+        - -c
+        - |
+          status_file=oslo-scan-status/smb-volume-release/status.json
+          cat "$status_file"
+          num_failures="$(grep -c '"status": "failed"' $status_file)"
+          echo ""
+          if [ "$num_failures" -eq 0 ]; then
+            echo "No failures found"
+            exit 0
+          else
+            echo "$num_failures failures found! Please check your norsk-viewers pipelines specified in the status.json and resolve the errors. Contact the OSL team if you need help."
+            exit 1
+          fi
