copy openldap release into collected tarballs directory
[#154852841](https://www.pivotaltracker.com/story/show/#154852841)

diff --git a/scripts/ci/collect-tarballs b/scripts/ci/collect-tarballs
--- a/scripts/ci/collect-tarballs
+++ b/scripts/ci/collect-tarballs
@@ -27,7 +27,7 @@ collect_versions() {
   fi
 
   if [ ! -d ${ROOT_DIR}/openldap-version ]; then
-    echo "[ERROR] ecs-version input is missing."
+    echo "[ERROR] openldap-version input is missing."
     exit 1
   fi
 
@@ -78,18 +78,18 @@ check_params() {
     echo "[ERROR] ecs-tarball input is missing."
     exit 1
   fi
-
+  if [ ! -d ${ROOT_DIR}/openldap-tarball ]; then
+    echo "[ERROR] openldap-tarball input is missing."
+    exit 1
+  fi
   if [ ! -d ${ROOT_DIR}/cephfs-tarball ]; then
     echo "[ERROR] cephfs-tarball input is missing."
     exit 1
   fi
-
   if [ ! -d ${ROOT_DIR}/smb-tarball ]; then
     echo "[ERROR] smb-tarball input is missing."
     exit 1
   fi
-
-
   if [ -z "${DIEGO_VERSION}" ]; then
     echo "[ERROR] DIEGO_VERSION is missing."
     exit 1
@@ -141,6 +141,7 @@ collect_tarballs() {
   cp ${ROOT_DIR}/efs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/efs.tgz
   cp ${ROOT_DIR}/csi-local-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/csi-local.tgz
   cp ${ROOT_DIR}/ecs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/ecs.tgz
+  cp ${ROOT_DIR}/openldap-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/openldap.tgz
   cp ${ROOT_DIR}/local-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/local.tgz
   cp ${ROOT_DIR}/cephfs-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/cephfs.tgz
   cp ${ROOT_DIR}/smb-tarball/*.tgz ${ROOT_DIR}/collected-tarballs/smb.tgz
